### ISSUE TITLE
gitlab ci hang up

### ISSUE THREAD

**Issue by LorenzoLeonardo** [LukeMathWalker/wiremock-rs#119] opened 2023-06-08 21:23 UTC
Hello

I am experiencing hang up in gitlab CI when using PUT method during unit test. It will work fine if I run the test in my local machine, but when it is already in gitlab CI, it seems the wiremock server doesn't respond. The curl perform is waiting forever.

**Comment by LukeMathWalker** [comment] 2023-06-09 08:59
Unless you provide us with a way to reproduce it on our machines (or some telemetry data explaining what's going on), I don't think we'll be able to troubleshoot the issue.

**Comment by LorenzoLeonardo** [comment] 2023-06-09 12:21
> Unless you provide us with a way to reproduce it on our machines (or some telemetry data explaining what's going on), I don't think we'll be able to troubleshoot the issue.

https://github.com/LukeMathWalker/wiremock-rs/pull/118

Please use this Sample code and commit it into gitlab with CI enabled with tests setup in yml file.

**Comment by LorenzoLeonardo** [comment] 2023-06-09 12:22
GET and POST is working well, only PUT method that server doesn't respond

**Comment by LukeMathWalker** [comment] 2023-06-09 13:40
This is way beyond what I'm willing to do for resolving a bug report (for free) on this OSS project, I'm sorry.

The issue could be in GitLab, in the curl crate or in wiremock and it could easily take me hours to pin it down since I'm not familiar with the first two.

**Closed** 2023-06-09 13:40 UTC
